In [70]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
x = pd.DataFrame(iris.data, columns=[iris.feature_names])
y = pd.Series(iris.target)

In [71]:
x.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


In [72]:
y.value_counts()

0    50
1    50
2    50
dtype: int64

In [73]:
#pip install keras==2.1.5 -i https://pypi.tuna.tsinghua.edu.cn/simple
#pip install --upgrade pip
#pip install tensorflow
#pip install tf-nightly

In [74]:
import tensorflow
import keras
from keras.utils import np_utils
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D,Dropout
from tensorflow.keras.layers import Dense, Activation, Flatten
from tensorflow.keras.utils import to_categorical
from tensorflow.keras import backend as K 
from sklearn.model_selection import train_test_split
from tensorflow.keras import callbacks
y_convertido = np_utils.to_categorical(y) #convertendo a coluna de valores em uma matriz de classes (one hot encoding)

In [75]:
y_convertido

array([[1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
 

In [76]:
from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y_convertido, test_size = 0.3)# 30% para teste

In [77]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

In [78]:
modelo = Sequential()
#Construimos a rede neural adicionando camadas por meio do comando ".add". O primeiro argumento consiste no nùmero de neurônios
#que aquela camada terá. Também podemos informar o modelo de inicialização das variáveis e a função de ativação nessa camada.
modelo.add(Dense(10, input_dim=4, kernel_initializer='normal', activation='relu')) #input_dim é a quantidade de neurônios de
#entrada, que nesse caso são 4 variáveis preditoras
modelo.add(Dense(3, kernel_initializer='normal', activation='softmax')) #Essa é a saida (3 neurônios pois são 3 classes)
#A função softmax para a saída costuma ser usada em problemas de classificação. Ela dá como resultado probabilidades de pertencer
#a cada uma das classes (softmax / sigmoid / relu)

In [79]:
otimizador = keras.optimizers.SGD()

In [80]:
x_treino.shape

(105, 4)

In [81]:
modelo.compile(loss='categorical_crossentropy', optimizer=otimizador, metrics=['acc']) #"acc" é a metrica de acurácia
modelo.fit(x_treino, y_treino, epochs=1000, batch_size=105, validation_data=(x_teste, y_teste), verbose=1)

Epoch 1/1000
1/1 [==============================] - 0s 470ms/step - loss: 1.0970 - acc: 0.3333 - val_loss: 1.0989 - val_acc: 0.3333
Epoch 2/1000
1/1 [==============================] - 0s 30ms/step - loss: 1.0968 - acc: 0.3333 - val_loss: 1.0987 - val_acc: 0.3333
Epoch 3/1000
1/1 [==============================] - 0s 31ms/step - loss: 1.0966 - acc: 0.3333 - val_loss: 1.0986 - val_acc: 0.3333
Epoch 4/1000
1/1 [==============================] - 0s 34ms/step - loss: 1.0964 - acc: 0.3333 - val_loss: 1.0984 - val_acc: 0.3333
Epoch 5/1000
1/1 [==============================] - 0s 31ms/step - loss: 1.0962 - acc: 0.3333 - val_loss: 1.0983 - val_acc: 0.3333
Epoch 6/1000
1/1 [==============================] - 0s 30ms/step - loss: 1.0960 - acc: 0.3333 - val_loss: 1.0981 - val_acc: 0.3333
Epoch 7/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0958 - acc: 0.3333 - val_loss: 1.0980 - val_acc: 0.3333
Epoch 8/1000
1/1 [==============================] - 0s 33ms/step - loss: 1.0956 - 

1/1 [==============================] - 0s 36ms/step - loss: 1.0838 - acc: 0.3333 - val_loss: 1.0870 - val_acc: 0.3333
Epoch 64/1000
1/1 [==============================] - 0s 36ms/step - loss: 1.0835 - acc: 0.3333 - val_loss: 1.0867 - val_acc: 0.3333
Epoch 65/1000
1/1 [==============================] - 0s 31ms/step - loss: 1.0832 - acc: 0.3333 - val_loss: 1.0864 - val_acc: 0.3333
Epoch 66/1000
1/1 [==============================] - 0s 31ms/step - loss: 1.0829 - acc: 0.3333 - val_loss: 1.0861 - val_acc: 0.3333
Epoch 67/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0826 - acc: 0.3333 - val_loss: 1.0858 - val_acc: 0.3333
Epoch 68/1000
1/1 [==============================] - 0s 30ms/step - loss: 1.0823 - acc: 0.3333 - val_loss: 1.0855 - val_acc: 0.3333
Epoch 69/1000
1/1 [==============================] - 0s 28ms/step - loss: 1.0819 - acc: 0.3333 - val_loss: 1.0852 - val_acc: 0.3333
Epoch 70/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0816 - acc: 0.

Epoch 125/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0547 - acc: 0.3333 - val_loss: 1.0576 - val_acc: 0.3556
Epoch 126/1000
1/1 [==============================] - 0s 28ms/step - loss: 1.0540 - acc: 0.3333 - val_loss: 1.0569 - val_acc: 0.3556
Epoch 127/1000
1/1 [==============================] - 0s 30ms/step - loss: 1.0533 - acc: 0.3333 - val_loss: 1.0562 - val_acc: 0.3556
Epoch 128/1000
1/1 [==============================] - 0s 30ms/step - loss: 1.0526 - acc: 0.3333 - val_loss: 1.0555 - val_acc: 0.3556
Epoch 129/1000
1/1 [==============================] - 0s 32ms/step - loss: 1.0519 - acc: 0.3333 - val_loss: 1.0548 - val_acc: 0.3556
Epoch 130/1000
1/1 [==============================] - 0s 30ms/step - loss: 1.0512 - acc: 0.3333 - val_loss: 1.0541 - val_acc: 0.3556
Epoch 131/1000
1/1 [==============================] - 0s 28ms/step - loss: 1.0505 - acc: 0.3333 - val_loss: 1.0534 - val_acc: 0.3556
Epoch 132/1000
1/1 [==============================] - 0s 31ms/step - 

1/1 [==============================] - 0s 31ms/step - loss: 0.9980 - acc: 0.6667 - val_loss: 1.0016 - val_acc: 0.6222
Epoch 187/1000
1/1 [==============================] - 0s 41ms/step - loss: 0.9968 - acc: 0.6667 - val_loss: 1.0004 - val_acc: 0.6222
Epoch 188/1000
1/1 [==============================] - 0s 32ms/step - loss: 0.9956 - acc: 0.6667 - val_loss: 0.9993 - val_acc: 0.6222
Epoch 189/1000
1/1 [==============================] - 0s 33ms/step - loss: 0.9944 - acc: 0.6667 - val_loss: 0.9981 - val_acc: 0.6222
Epoch 190/1000
1/1 [==============================] - 0s 32ms/step - loss: 0.9932 - acc: 0.6667 - val_loss: 0.9969 - val_acc: 0.6222
Epoch 191/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.9920 - acc: 0.6762 - val_loss: 0.9957 - val_acc: 0.6222
Epoch 192/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.9908 - acc: 0.6762 - val_loss: 0.9945 - val_acc: 0.6222
Epoch 193/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.9896 - 

Epoch 248/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.9171 - acc: 0.6857 - val_loss: 0.9225 - val_acc: 0.6222
Epoch 249/1000
1/1 [==============================] - 0s 32ms/step - loss: 0.9157 - acc: 0.6857 - val_loss: 0.9212 - val_acc: 0.6222
Epoch 250/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.9144 - acc: 0.6857 - val_loss: 0.9199 - val_acc: 0.6222
Epoch 251/1000
1/1 [==============================] - 0s 36ms/step - loss: 0.9131 - acc: 0.6857 - val_loss: 0.9186 - val_acc: 0.6222
Epoch 252/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.9117 - acc: 0.6857 - val_loss: 0.9174 - val_acc: 0.6222
Epoch 253/1000
1/1 [==============================] - 0s 32ms/step - loss: 0.9104 - acc: 0.6857 - val_loss: 0.9161 - val_acc: 0.6222
Epoch 254/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.9091 - acc: 0.6857 - val_loss: 0.9149 - val_acc: 0.6222
Epoch 255/1000
1/1 [==============================] - 0s 32ms/step - 

1/1 [==============================] - 0s 32ms/step - loss: 0.8445 - acc: 0.6857 - val_loss: 0.8533 - val_acc: 0.6222
Epoch 310/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.8434 - acc: 0.6857 - val_loss: 0.8523 - val_acc: 0.6222
Epoch 311/1000
1/1 [==============================] - 0s 33ms/step - loss: 0.8424 - acc: 0.6857 - val_loss: 0.8513 - val_acc: 0.6222
Epoch 312/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.8413 - acc: 0.6857 - val_loss: 0.8504 - val_acc: 0.6222
Epoch 313/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.8403 - acc: 0.6857 - val_loss: 0.8494 - val_acc: 0.6222
Epoch 314/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.8392 - acc: 0.6857 - val_loss: 0.8484 - val_acc: 0.6222
Epoch 315/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.8382 - acc: 0.6857 - val_loss: 0.8474 - val_acc: 0.6222
Epoch 316/1000
1/1 [==============================] - 0s 35ms/step - loss: 0.8372 - 

Epoch 371/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.7861 - acc: 0.6857 - val_loss: 0.7979 - val_acc: 0.6222
Epoch 372/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.7853 - acc: 0.6857 - val_loss: 0.7971 - val_acc: 0.6222
Epoch 373/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.7845 - acc: 0.6857 - val_loss: 0.7963 - val_acc: 0.6222
Epoch 374/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.7836 - acc: 0.6857 - val_loss: 0.7955 - val_acc: 0.6222
Epoch 375/1000
1/1 [==============================] - 0s 33ms/step - loss: 0.7828 - acc: 0.6857 - val_loss: 0.7947 - val_acc: 0.6222
Epoch 376/1000
1/1 [==============================] - 0s 32ms/step - loss: 0.7820 - acc: 0.6857 - val_loss: 0.7939 - val_acc: 0.6222
Epoch 377/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.7812 - acc: 0.6857 - val_loss: 0.7931 - val_acc: 0.6222
Epoch 378/1000
1/1 [==============================] - 0s 26ms/step - 

1/1 [==============================] - 0s 47ms/step - loss: 0.7404 - acc: 0.6857 - val_loss: 0.7541 - val_acc: 0.6222
Epoch 433/1000
1/1 [==============================] - 0s 49ms/step - loss: 0.7397 - acc: 0.6857 - val_loss: 0.7535 - val_acc: 0.6222
Epoch 434/1000
1/1 [==============================] - 0s 35ms/step - loss: 0.7390 - acc: 0.6857 - val_loss: 0.7528 - val_acc: 0.6222
Epoch 435/1000
1/1 [==============================] - 0s 41ms/step - loss: 0.7384 - acc: 0.6857 - val_loss: 0.7522 - val_acc: 0.6222
Epoch 436/1000
1/1 [==============================] - 0s 36ms/step - loss: 0.7377 - acc: 0.6857 - val_loss: 0.7516 - val_acc: 0.6222
Epoch 437/1000
1/1 [==============================] - 0s 36ms/step - loss: 0.7370 - acc: 0.6857 - val_loss: 0.7510 - val_acc: 0.6222
Epoch 438/1000
1/1 [==============================] - 0s 32ms/step - loss: 0.7364 - acc: 0.6857 - val_loss: 0.7503 - val_acc: 0.6222
Epoch 439/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.7357 - 

Epoch 494/1000
1/1 [==============================] - 0s 33ms/step - loss: 0.7021 - acc: 0.6857 - val_loss: 0.7184 - val_acc: 0.6222
Epoch 495/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.7015 - acc: 0.6857 - val_loss: 0.7179 - val_acc: 0.6222
Epoch 496/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.7010 - acc: 0.6857 - val_loss: 0.7173 - val_acc: 0.6222
Epoch 497/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.7004 - acc: 0.6857 - val_loss: 0.7168 - val_acc: 0.6222
Epoch 498/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.6998 - acc: 0.6857 - val_loss: 0.7163 - val_acc: 0.6222
Epoch 499/1000
1/1 [==============================] - 0s 35ms/step - loss: 0.6993 - acc: 0.6857 - val_loss: 0.7158 - val_acc: 0.6222
Epoch 500/1000
1/1 [==============================] - 0s 35ms/step - loss: 0.6987 - acc: 0.6857 - val_loss: 0.7153 - val_acc: 0.6222
Epoch 501/1000
1/1 [==============================] - 0s 34ms/step - 

1/1 [==============================] - 0s 32ms/step - loss: 0.6704 - acc: 0.6857 - val_loss: 0.6893 - val_acc: 0.6222
Epoch 556/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.6699 - acc: 0.6857 - val_loss: 0.6889 - val_acc: 0.6222
Epoch 557/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.6694 - acc: 0.6857 - val_loss: 0.6885 - val_acc: 0.6222
Epoch 558/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.6689 - acc: 0.6857 - val_loss: 0.6880 - val_acc: 0.6222
Epoch 559/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.6685 - acc: 0.6857 - val_loss: 0.6876 - val_acc: 0.6222
Epoch 560/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.6680 - acc: 0.6857 - val_loss: 0.6872 - val_acc: 0.6222
Epoch 561/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.6675 - acc: 0.6857 - val_loss: 0.6867 - val_acc: 0.6222
Epoch 562/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.6670 - 

Epoch 617/1000
1/1 [==============================] - 0s 32ms/step - loss: 0.6427 - acc: 0.6857 - val_loss: 0.6644 - val_acc: 0.6222
Epoch 618/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.6423 - acc: 0.6857 - val_loss: 0.6640 - val_acc: 0.6222
Epoch 619/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.6419 - acc: 0.6857 - val_loss: 0.6636 - val_acc: 0.6222
Epoch 620/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.6415 - acc: 0.6857 - val_loss: 0.6633 - val_acc: 0.6222
Epoch 621/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.6411 - acc: 0.6857 - val_loss: 0.6629 - val_acc: 0.6222
Epoch 622/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.6407 - acc: 0.6952 - val_loss: 0.6625 - val_acc: 0.6222
Epoch 623/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.6403 - acc: 0.6952 - val_loss: 0.6622 - val_acc: 0.6222
Epoch 624/1000
1/1 [==============================] - 0s 30ms/step - 

1/1 [==============================] - 0s 28ms/step - loss: 0.6191 - acc: 0.6952 - val_loss: 0.6434 - val_acc: 0.6222
Epoch 679/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.6187 - acc: 0.6952 - val_loss: 0.6431 - val_acc: 0.6222
Epoch 680/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.6184 - acc: 0.6952 - val_loss: 0.6428 - val_acc: 0.6222
Epoch 681/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.6180 - acc: 0.6952 - val_loss: 0.6424 - val_acc: 0.6222
Epoch 682/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.6176 - acc: 0.6952 - val_loss: 0.6421 - val_acc: 0.6222
Epoch 683/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.6173 - acc: 0.6952 - val_loss: 0.6418 - val_acc: 0.6222
Epoch 684/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.6169 - acc: 0.6952 - val_loss: 0.6415 - val_acc: 0.6222
Epoch 685/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.6166 - 

Epoch 740/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.5981 - acc: 0.6952 - val_loss: 0.6246 - val_acc: 0.6222
Epoch 741/1000
1/1 [==============================] - 0s 33ms/step - loss: 0.5977 - acc: 0.6952 - val_loss: 0.6244 - val_acc: 0.6222
Epoch 742/1000
1/1 [==============================] - 0s 47ms/step - loss: 0.5974 - acc: 0.6952 - val_loss: 0.6241 - val_acc: 0.6222
Epoch 743/1000
1/1 [==============================] - 0s 34ms/step - loss: 0.5971 - acc: 0.6952 - val_loss: 0.6238 - val_acc: 0.6222
Epoch 744/1000
1/1 [==============================] - 0s 38ms/step - loss: 0.5968 - acc: 0.6952 - val_loss: 0.6235 - val_acc: 0.6222
Epoch 745/1000
1/1 [==============================] - 0s 37ms/step - loss: 0.5965 - acc: 0.6952 - val_loss: 0.6233 - val_acc: 0.6222
Epoch 746/1000
1/1 [==============================] - 0s 33ms/step - loss: 0.5962 - acc: 0.6952 - val_loss: 0.6230 - val_acc: 0.6222
Epoch 747/1000
1/1 [==============================] - 0s 42ms/step - 

1/1 [==============================] - 0s 40ms/step - loss: 0.5798 - acc: 0.6952 - val_loss: 0.6085 - val_acc: 0.6222
Epoch 802/1000
1/1 [==============================] - 0s 32ms/step - loss: 0.5795 - acc: 0.6952 - val_loss: 0.6083 - val_acc: 0.6222
Epoch 803/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.5792 - acc: 0.6952 - val_loss: 0.6080 - val_acc: 0.6222
Epoch 804/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.5790 - acc: 0.6952 - val_loss: 0.6078 - val_acc: 0.6222
Epoch 805/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.5787 - acc: 0.6952 - val_loss: 0.6075 - val_acc: 0.6222
Epoch 806/1000
1/1 [==============================] - 0s 34ms/step - loss: 0.5784 - acc: 0.6952 - val_loss: 0.6073 - val_acc: 0.6222
Epoch 807/1000
1/1 [==============================] - 0s 33ms/step - loss: 0.5781 - acc: 0.6952 - val_loss: 0.6070 - val_acc: 0.6222
Epoch 808/1000
1/1 [==============================] - 0s 35ms/step - loss: 0.5778 - 

Epoch 863/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.5634 - acc: 0.7143 - val_loss: 0.5938 - val_acc: 0.6222
Epoch 864/1000
1/1 [==============================] - 0s 37ms/step - loss: 0.5631 - acc: 0.7143 - val_loss: 0.5936 - val_acc: 0.6222
Epoch 865/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.5629 - acc: 0.7238 - val_loss: 0.5934 - val_acc: 0.6222
Epoch 866/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.5626 - acc: 0.7238 - val_loss: 0.5932 - val_acc: 0.6222
Epoch 867/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.5624 - acc: 0.7238 - val_loss: 0.5929 - val_acc: 0.6222
Epoch 868/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.5621 - acc: 0.7238 - val_loss: 0.5927 - val_acc: 0.6222
Epoch 869/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5619 - acc: 0.7238 - val_loss: 0.5925 - val_acc: 0.6222
Epoch 870/1000
1/1 [==============================] - 0s 30ms/step - 

1/1 [==============================] - 0s 29ms/step - loss: 0.5489 - acc: 0.7238 - val_loss: 0.5810 - val_acc: 0.6222
Epoch 925/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.5487 - acc: 0.7238 - val_loss: 0.5808 - val_acc: 0.6222
Epoch 926/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.5484 - acc: 0.7238 - val_loss: 0.5806 - val_acc: 0.6222
Epoch 927/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.5482 - acc: 0.7238 - val_loss: 0.5804 - val_acc: 0.6222
Epoch 928/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.5480 - acc: 0.7238 - val_loss: 0.5802 - val_acc: 0.6222
Epoch 929/1000
1/1 [==============================] - 0s 33ms/step - loss: 0.5478 - acc: 0.7238 - val_loss: 0.5800 - val_acc: 0.6222
Epoch 930/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.5476 - acc: 0.7238 - val_loss: 0.5798 - val_acc: 0.6222
Epoch 931/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5473 - 

Epoch 986/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5357 - acc: 0.7333 - val_loss: 0.5692 - val_acc: 0.6222
Epoch 987/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5355 - acc: 0.7333 - val_loss: 0.5690 - val_acc: 0.6222
Epoch 988/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.5353 - acc: 0.7333 - val_loss: 0.5688 - val_acc: 0.6222
Epoch 989/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.5351 - acc: 0.7333 - val_loss: 0.5687 - val_acc: 0.6222
Epoch 990/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5349 - acc: 0.7333 - val_loss: 0.5685 - val_acc: 0.6222
Epoch 991/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.5347 - acc: 0.7333 - val_loss: 0.5683 - val_acc: 0.6222
Epoch 992/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.5345 - acc: 0.7333 - val_loss: 0.5681 - val_acc: 0.6222
Epoch 993/1000
1/1 [==============================] - 0s 31ms/step - 

In [82]:
predicoes = modelo.predict(x_teste)
print(predicoes)

2/2 [==============================] - 0s 2ms/step
[[0.02 0.42 0.56]
 [0.02 0.43 0.56]
 [0.69 0.21 0.10]
 [0.00 0.34 0.66]
 [0.01 0.41 0.57]
 [0.03 0.45 0.52]
 [0.00 0.35 0.64]
 [0.00 0.34 0.66]
 [0.02 0.44 0.54]
 [0.00 0.34 0.65]
 [0.00 0.30 0.70]
 [0.02 0.43 0.55]
 [0.03 0.45 0.52]
 [0.03 0.44 0.53]
 [0.00 0.33 0.66]
 [0.04 0.46 0.50]
 [0.70 0.20 0.10]
 [0.70 0.20 0.10]
 [0.70 0.20 0.10]
 [0.01 0.37 0.62]
 [0.03 0.44 0.53]
 [0.70 0.20 0.10]
 [0.70 0.20 0.10]
 [0.01 0.39 0.60]
 [0.02 0.43 0.55]
 [0.00 0.36 0.63]
 [0.02 0.43 0.55]
 [0.01 0.38 0.62]
 [0.05 0.46 0.48]
 [0.03 0.45 0.52]
 [0.01 0.42 0.57]
 [0.01 0.38 0.61]
 [0.70 0.20 0.10]
 [0.01 0.41 0.58]
 [0.70 0.20 0.10]
 [0.70 0.20 0.10]
 [0.70 0.20 0.10]
 [0.00 0.28 0.72]
 [0.70 0.20 0.10]
 [0.70 0.20 0.10]
 [0.03 0.45 0.52]
 [0.01 0.40 0.59]
 [0.02 0.43 0.55]
 [0.00 0.37 0.62]
 [0.70 0.20 0.10]]


In [83]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})
print(predicoes)

[[0.02 0.42 0.56]
 [0.02 0.43 0.56]
 [0.69 0.21 0.10]
 [0.00 0.34 0.66]
 [0.01 0.41 0.57]
 [0.03 0.45 0.52]
 [0.00 0.35 0.64]
 [0.00 0.34 0.66]
 [0.02 0.44 0.54]
 [0.00 0.34 0.65]
 [0.00 0.30 0.70]
 [0.02 0.43 0.55]
 [0.03 0.45 0.52]
 [0.03 0.44 0.53]
 [0.00 0.33 0.66]
 [0.04 0.46 0.50]
 [0.70 0.20 0.10]
 [0.70 0.20 0.10]
 [0.70 0.20 0.10]
 [0.01 0.37 0.62]
 [0.03 0.44 0.53]
 [0.70 0.20 0.10]
 [0.70 0.20 0.10]
 [0.01 0.39 0.60]
 [0.02 0.43 0.55]
 [0.00 0.36 0.63]
 [0.02 0.43 0.55]
 [0.01 0.38 0.62]
 [0.05 0.46 0.48]
 [0.03 0.45 0.52]
 [0.01 0.42 0.57]
 [0.01 0.38 0.61]
 [0.70 0.20 0.10]
 [0.01 0.41 0.58]
 [0.70 0.20 0.10]
 [0.70 0.20 0.10]
 [0.70 0.20 0.10]
 [0.00 0.28 0.72]
 [0.70 0.20 0.10]
 [0.70 0.20 0.10]
 [0.03 0.45 0.52]
 [0.01 0.40 0.59]
 [0.02 0.43 0.55]
 [0.00 0.37 0.62]
 [0.70 0.20 0.10]]
