In [27]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
x = pd.DataFrame(iris.data, columns=[iris.feature_names])
y = pd.Series(iris.target)

In [28]:
x.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


In [29]:
y.value_counts()

0    50
1    50
2    50
Name: count, dtype: int64

In [30]:
# Instale o Anaconda - Ultima versão
# Abra Anaconda Navigator
# Aba - Environments - Crie um novo perfil: tensorflow / python: 3.7
#!pip3 install keras==2.1.5 -i https://pypi.tuna.tsinghua.edu.cn/simple
#!pip3 install tensorflow
#!pip3 install tensorflow-gpu==1.5.0
#!pip3 install tf-nightly
#!pip3 install np_utils

In [31]:
import tensorflow
import keras
from tensorflow.python.keras.utils import np_utils
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D,Dropout
from tensorflow.keras.layers import Dense, Activation, Flatten
from tensorflow.keras.utils import to_categorical
from tensorflow.keras import backend as K 
from sklearn.model_selection import train_test_split
from tensorflow.keras import callbacks
y_convertido = np_utils.to_categorical(y) #convertendo a coluna de valores em uma matriz de classes (one hot encoding)

In [32]:
y_convertido

array([[1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
 

In [33]:
from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y_convertido, test_size = 0.3)# 30% para teste

In [34]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

In [35]:
modelo = Sequential()
#Construimos a rede neural adicionando camadas por meio do comando ".add". O primeiro argumento consiste no nùmero de neurônios
#que aquela camada terá. Também podemos informar o modelo de inicialização das variáveis e a função de ativação nessa camada.
modelo.add(Dense(10, input_dim=4, kernel_initializer='normal', activation='relu')) #input_dim é a quantidade de neurônios de
#entrada, que nesse caso são 4 variáveis preditoras
modelo.add(Dense(3, kernel_initializer='normal', activation='softmax')) #Essa é a saida (3 neurônios pois são 3 classes)
#A função softmax para a saída costuma ser usada em problemas de classificação. Ela dá como resultado probabilidades de pertencer
#a cada uma das classes (softmax / sigmoid / relu)

In [36]:
otimizador = keras.optimizers.SGD()

In [37]:
x_treino.shape

(105, 4)

In [38]:
modelo.compile(loss='categorical_crossentropy', optimizer=otimizador, metrics=['acc']) #"acc" é a metrica de acurácia
modelo.fit(x_treino, y_treino, epochs=1000, batch_size=105, validation_data=(x_teste, y_teste), verbose=1)

Epoch 1/1000
1/1 [==============================] - 0s 403ms/step - loss: 1.0954 - acc: 0.5429 - val_loss: 1.0967 - val_acc: 0.4667
Epoch 2/1000
1/1 [==============================] - 0s 30ms/step - loss: 1.0950 - acc: 0.5429 - val_loss: 1.0966 - val_acc: 0.4000
Epoch 3/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0947 - acc: 0.4286 - val_loss: 1.0966 - val_acc: 0.3111
Epoch 4/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0944 - acc: 0.3905 - val_loss: 1.0965 - val_acc: 0.2667
Epoch 5/1000
1/1 [==============================] - 0s 28ms/step - loss: 1.0941 - acc: 0.3714 - val_loss: 1.0965 - val_acc: 0.2667
Epoch 6/1000
1/1 [==============================] - 0s 28ms/step - loss: 1.0939 - acc: 0.3619 - val_loss: 1.0965 - val_acc: 0.2667
Epoch 7/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0936 - acc: 0.3619 - val_loss: 1.0964 - val_acc: 0.2667
Epoch 8/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0934 - 

1/1 [==============================] - 0s 28ms/step - loss: 1.0730 - acc: 0.3619 - val_loss: 1.0905 - val_acc: 0.2667
Epoch 64/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0725 - acc: 0.3619 - val_loss: 1.0903 - val_acc: 0.2667
Epoch 65/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0720 - acc: 0.3619 - val_loss: 1.0901 - val_acc: 0.2667
Epoch 66/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0715 - acc: 0.3619 - val_loss: 1.0899 - val_acc: 0.2667
Epoch 67/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0710 - acc: 0.3619 - val_loss: 1.0898 - val_acc: 0.2667
Epoch 68/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0705 - acc: 0.3619 - val_loss: 1.0896 - val_acc: 0.2667
Epoch 69/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0700 - acc: 0.3619 - val_loss: 1.0894 - val_acc: 0.2667
Epoch 70/1000
1/1 [==============================] - 0s 30ms/step - loss: 1.0695 - acc: 0.

Epoch 125/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0341 - acc: 0.3619 - val_loss: 1.0718 - val_acc: 0.2667
Epoch 126/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0333 - acc: 0.3619 - val_loss: 1.0714 - val_acc: 0.2667
Epoch 127/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0326 - acc: 0.3619 - val_loss: 1.0708 - val_acc: 0.2667
Epoch 128/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0318 - acc: 0.3619 - val_loss: 1.0703 - val_acc: 0.2667
Epoch 129/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0310 - acc: 0.3619 - val_loss: 1.0698 - val_acc: 0.2667
Epoch 130/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0303 - acc: 0.3619 - val_loss: 1.0693 - val_acc: 0.2667
Epoch 131/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0295 - acc: 0.3619 - val_loss: 1.0687 - val_acc: 0.2667
Epoch 132/1000
1/1 [==============================] - 0s 27ms/step - 

1/1 [==============================] - 0s 31ms/step - loss: 0.9783 - acc: 0.3619 - val_loss: 1.0214 - val_acc: 0.2667
Epoch 187/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.9772 - acc: 0.3619 - val_loss: 1.0203 - val_acc: 0.2667
Epoch 188/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.9761 - acc: 0.3619 - val_loss: 1.0191 - val_acc: 0.2667
Epoch 189/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.9750 - acc: 0.3619 - val_loss: 1.0180 - val_acc: 0.2667
Epoch 190/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.9739 - acc: 0.3619 - val_loss: 1.0169 - val_acc: 0.2667
Epoch 191/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.9728 - acc: 0.3619 - val_loss: 1.0157 - val_acc: 0.2667
Epoch 192/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.9716 - acc: 0.3619 - val_loss: 1.0145 - val_acc: 0.2667
Epoch 193/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.9705 - 

Epoch 248/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.9000 - acc: 0.6286 - val_loss: 0.9407 - val_acc: 0.6667
Epoch 249/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.8987 - acc: 0.6286 - val_loss: 0.9396 - val_acc: 0.6667
Epoch 250/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.8975 - acc: 0.6286 - val_loss: 0.9384 - val_acc: 0.6667
Epoch 251/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.8963 - acc: 0.6286 - val_loss: 0.9373 - val_acc: 0.6667
Epoch 252/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.8950 - acc: 0.6286 - val_loss: 0.9361 - val_acc: 0.6667
Epoch 253/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.8938 - acc: 0.6381 - val_loss: 0.9350 - val_acc: 0.6667
Epoch 254/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.8926 - acc: 0.6381 - val_loss: 0.9338 - val_acc: 0.6667
Epoch 255/1000
1/1 [==============================] - 0s 27ms/step - 

1/1 [==============================] - 0s 26ms/step - loss: 0.8329 - acc: 0.6667 - val_loss: 0.8770 - val_acc: 0.6667
Epoch 310/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.8320 - acc: 0.6667 - val_loss: 0.8760 - val_acc: 0.6667
Epoch 311/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.8310 - acc: 0.6667 - val_loss: 0.8751 - val_acc: 0.6667
Epoch 312/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.8301 - acc: 0.6667 - val_loss: 0.8742 - val_acc: 0.6667
Epoch 313/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.8292 - acc: 0.6667 - val_loss: 0.8732 - val_acc: 0.6667
Epoch 314/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.8283 - acc: 0.6667 - val_loss: 0.8723 - val_acc: 0.6667
Epoch 315/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.8274 - acc: 0.6667 - val_loss: 0.8714 - val_acc: 0.6667
Epoch 316/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.8265 - 

Epoch 371/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.7819 - acc: 0.6667 - val_loss: 0.8239 - val_acc: 0.6667
Epoch 372/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.7811 - acc: 0.6667 - val_loss: 0.8231 - val_acc: 0.6667
Epoch 373/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.7804 - acc: 0.6667 - val_loss: 0.8223 - val_acc: 0.6667
Epoch 374/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.7797 - acc: 0.6667 - val_loss: 0.8215 - val_acc: 0.6667
Epoch 375/1000
1/1 [==============================] - 0s 33ms/step - loss: 0.7790 - acc: 0.6667 - val_loss: 0.8208 - val_acc: 0.6667
Epoch 376/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.7783 - acc: 0.6667 - val_loss: 0.8200 - val_acc: 0.6667
Epoch 377/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.7775 - acc: 0.6667 - val_loss: 0.8192 - val_acc: 0.6667
Epoch 378/1000
1/1 [==============================] - 0s 28ms/step - 

1/1 [==============================] - 0s 30ms/step - loss: 0.7421 - acc: 0.6667 - val_loss: 0.7802 - val_acc: 0.6667
Epoch 433/1000
1/1 [==============================] - 0s 34ms/step - loss: 0.7415 - acc: 0.6667 - val_loss: 0.7796 - val_acc: 0.6667
Epoch 434/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.7410 - acc: 0.6667 - val_loss: 0.7789 - val_acc: 0.6667
Epoch 435/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.7404 - acc: 0.6667 - val_loss: 0.7783 - val_acc: 0.6667
Epoch 436/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.7398 - acc: 0.6667 - val_loss: 0.7776 - val_acc: 0.6667
Epoch 437/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.7392 - acc: 0.6667 - val_loss: 0.7770 - val_acc: 0.6667
Epoch 438/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.7387 - acc: 0.6667 - val_loss: 0.7763 - val_acc: 0.6667
Epoch 439/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.7381 - 

Epoch 494/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.7089 - acc: 0.6667 - val_loss: 0.7420 - val_acc: 0.6667
Epoch 495/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.7084 - acc: 0.6667 - val_loss: 0.7414 - val_acc: 0.6667
Epoch 496/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.7079 - acc: 0.6667 - val_loss: 0.7408 - val_acc: 0.6667
Epoch 497/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.7074 - acc: 0.6667 - val_loss: 0.7403 - val_acc: 0.6667
Epoch 498/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.7069 - acc: 0.6667 - val_loss: 0.7397 - val_acc: 0.6667
Epoch 499/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.7064 - acc: 0.6667 - val_loss: 0.7391 - val_acc: 0.6667
Epoch 500/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.7060 - acc: 0.6667 - val_loss: 0.7385 - val_acc: 0.6667
Epoch 501/1000
1/1 [==============================] - 0s 28ms/step - 

1/1 [==============================] - 0s 26ms/step - loss: 0.6805 - acc: 0.6667 - val_loss: 0.7093 - val_acc: 0.6667
Epoch 556/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.6800 - acc: 0.6667 - val_loss: 0.7088 - val_acc: 0.6667
Epoch 557/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.6796 - acc: 0.6667 - val_loss: 0.7084 - val_acc: 0.6667
Epoch 558/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.6792 - acc: 0.6667 - val_loss: 0.7079 - val_acc: 0.6667
Epoch 559/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.6787 - acc: 0.6667 - val_loss: 0.7074 - val_acc: 0.6667
Epoch 560/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.6783 - acc: 0.6667 - val_loss: 0.7069 - val_acc: 0.6667
Epoch 561/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.6779 - acc: 0.6667 - val_loss: 0.7065 - val_acc: 0.6667
Epoch 562/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.6774 - 

Epoch 617/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.6552 - acc: 0.6667 - val_loss: 0.6809 - val_acc: 0.6667
Epoch 618/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.6548 - acc: 0.6667 - val_loss: 0.6804 - val_acc: 0.6667
Epoch 619/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.6544 - acc: 0.6667 - val_loss: 0.6800 - val_acc: 0.6667
Epoch 620/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.6541 - acc: 0.6667 - val_loss: 0.6795 - val_acc: 0.6667
Epoch 621/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.6537 - acc: 0.6667 - val_loss: 0.6791 - val_acc: 0.6667
Epoch 622/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.6533 - acc: 0.6667 - val_loss: 0.6787 - val_acc: 0.6667
Epoch 623/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.6529 - acc: 0.6667 - val_loss: 0.6782 - val_acc: 0.6667
Epoch 624/1000
1/1 [==============================] - 0s 26ms/step - 

1/1 [==============================] - 0s 27ms/step - loss: 0.6333 - acc: 0.6762 - val_loss: 0.6555 - val_acc: 0.6667
Epoch 679/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.6330 - acc: 0.6762 - val_loss: 0.6552 - val_acc: 0.6667
Epoch 680/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.6326 - acc: 0.6762 - val_loss: 0.6548 - val_acc: 0.6667
Epoch 681/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.6323 - acc: 0.6762 - val_loss: 0.6544 - val_acc: 0.6667
Epoch 682/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.6319 - acc: 0.6762 - val_loss: 0.6540 - val_acc: 0.6667
Epoch 683/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.6316 - acc: 0.6762 - val_loss: 0.6536 - val_acc: 0.6667
Epoch 684/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.6313 - acc: 0.6762 - val_loss: 0.6532 - val_acc: 0.6667
Epoch 685/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.6309 - 

Epoch 740/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.6132 - acc: 0.6762 - val_loss: 0.6330 - val_acc: 0.6667
Epoch 741/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.6129 - acc: 0.6762 - val_loss: 0.6326 - val_acc: 0.6667
Epoch 742/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.6126 - acc: 0.6762 - val_loss: 0.6323 - val_acc: 0.6667
Epoch 743/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.6123 - acc: 0.6762 - val_loss: 0.6319 - val_acc: 0.6667
Epoch 744/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.6120 - acc: 0.6762 - val_loss: 0.6316 - val_acc: 0.6667
Epoch 745/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.6117 - acc: 0.6762 - val_loss: 0.6312 - val_acc: 0.6667
Epoch 746/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.6114 - acc: 0.6762 - val_loss: 0.6309 - val_acc: 0.6667
Epoch 747/1000
1/1 [==============================] - 0s 26ms/step - 

1/1 [==============================] - 0s 26ms/step - loss: 0.5956 - acc: 0.6762 - val_loss: 0.6130 - val_acc: 0.6889
Epoch 802/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.5953 - acc: 0.6762 - val_loss: 0.6127 - val_acc: 0.6889
Epoch 803/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5950 - acc: 0.6762 - val_loss: 0.6124 - val_acc: 0.6889
Epoch 804/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5947 - acc: 0.6857 - val_loss: 0.6121 - val_acc: 0.6889
Epoch 805/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5945 - acc: 0.6857 - val_loss: 0.6118 - val_acc: 0.6889
Epoch 806/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.5942 - acc: 0.6857 - val_loss: 0.6114 - val_acc: 0.6889
Epoch 807/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.5939 - acc: 0.6857 - val_loss: 0.6111 - val_acc: 0.6889
Epoch 808/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.5936 - 

Epoch 863/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5793 - acc: 0.6952 - val_loss: 0.5945 - val_acc: 0.6889
Epoch 864/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5790 - acc: 0.6952 - val_loss: 0.5942 - val_acc: 0.6889
Epoch 865/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.5788 - acc: 0.6952 - val_loss: 0.5939 - val_acc: 0.6889
Epoch 866/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5785 - acc: 0.6952 - val_loss: 0.5937 - val_acc: 0.6889
Epoch 867/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5783 - acc: 0.6952 - val_loss: 0.5934 - val_acc: 0.6889
Epoch 868/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.5780 - acc: 0.6952 - val_loss: 0.5931 - val_acc: 0.6889
Epoch 869/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.5778 - acc: 0.6952 - val_loss: 0.5928 - val_acc: 0.6889
Epoch 870/1000
1/1 [==============================] - 0s 26ms/step - 

1/1 [==============================] - 0s 26ms/step - loss: 0.5647 - acc: 0.6952 - val_loss: 0.5782 - val_acc: 0.6889
Epoch 925/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.5645 - acc: 0.6952 - val_loss: 0.5780 - val_acc: 0.6889
Epoch 926/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.5643 - acc: 0.6952 - val_loss: 0.5777 - val_acc: 0.6889
Epoch 927/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5640 - acc: 0.6952 - val_loss: 0.5774 - val_acc: 0.6889
Epoch 928/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.5638 - acc: 0.6952 - val_loss: 0.5772 - val_acc: 0.6889
Epoch 929/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5636 - acc: 0.6952 - val_loss: 0.5769 - val_acc: 0.6889
Epoch 930/1000
1/1 [==============================] - 0s 32ms/step - loss: 0.5634 - acc: 0.6952 - val_loss: 0.5767 - val_acc: 0.6889
Epoch 931/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.5631 - 

Epoch 986/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.5512 - acc: 0.7048 - val_loss: 0.5630 - val_acc: 0.6889
Epoch 987/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5510 - acc: 0.7048 - val_loss: 0.5628 - val_acc: 0.6889
Epoch 988/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5508 - acc: 0.7048 - val_loss: 0.5625 - val_acc: 0.6889
Epoch 989/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.5506 - acc: 0.7048 - val_loss: 0.5623 - val_acc: 0.6889
Epoch 990/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.5504 - acc: 0.7048 - val_loss: 0.5621 - val_acc: 0.6889
Epoch 991/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.5502 - acc: 0.7048 - val_loss: 0.5618 - val_acc: 0.6889
Epoch 992/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5500 - acc: 0.7048 - val_loss: 0.5616 - val_acc: 0.6889
Epoch 993/1000
1/1 [==============================] - 0s 26ms/step - 

In [39]:
predicoes = modelo.predict(x_teste)
print(predicoes)

2/2 [==============================] - 0s 2ms/step
[[0.66 0.23 0.11]
 [0.66 0.23 0.11]
 [0.66 0.23 0.11]
 [0.02 0.43 0.56]
 [0.00 0.34 0.65]
 [0.66 0.23 0.11]
 [0.01 0.39 0.60]
 [0.00 0.35 0.65]
 [0.00 0.36 0.64]
 [0.00 0.31 0.68]
 [0.66 0.23 0.11]
 [0.03 0.45 0.52]
 [0.00 0.24 0.76]
 [0.66 0.23 0.11]
 [0.08 0.48 0.44]
 [0.66 0.23 0.11]
 [0.02 0.43 0.55]
 [0.66 0.23 0.11]
 [0.66 0.23 0.11]
 [0.03 0.45 0.52]
 [0.66 0.23 0.11]
 [0.01 0.40 0.59]
 [0.03 0.45 0.52]
 [0.66 0.23 0.11]
 [0.66 0.23 0.11]
 [0.66 0.23 0.11]
 [0.66 0.23 0.11]
 [0.66 0.23 0.11]
 [0.01 0.39 0.60]
 [0.01 0.39 0.60]
 [0.00 0.33 0.66]
 [0.00 0.35 0.64]
 [0.66 0.23 0.11]
 [0.00 0.29 0.71]
 [0.02 0.43 0.56]
 [0.66 0.23 0.11]
 [0.02 0.42 0.56]
 [0.00 0.36 0.63]
 [0.02 0.42 0.56]
 [0.66 0.23 0.11]
 [0.02 0.43 0.55]
 [0.03 0.46 0.51]
 [0.02 0.43 0.55]
 [0.01 0.39 0.61]
 [0.01 0.42 0.57]]


In [26]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})
print(predicoes)

[[0.00 0.19 0.81]
 [0.05 0.66 0.29]
 [0.99 0.01 0.00]
 [0.01 0.53 0.46]
 [0.01 0.44 0.55]
 [0.00 0.41 0.59]
 [0.94 0.06 0.00]
 [0.03 0.67 0.30]
 [0.00 0.30 0.70]
 [0.00 0.42 0.58]
 [0.00 0.20 0.80]
 [0.00 0.25 0.75]
 [0.90 0.10 0.00]
 [0.07 0.68 0.25]
 [0.97 0.03 0.00]
 [0.00 0.32 0.67]
 [0.02 0.67 0.31]
 [0.94 0.06 0.00]
 [0.00 0.08 0.92]
 [0.03 0.66 0.31]
 [0.06 0.72 0.22]
 [0.04 0.66 0.30]
 [0.11 0.68 0.22]
 [0.05 0.74 0.21]
 [0.98 0.02 0.00]
 [0.00 0.19 0.81]
 [0.96 0.04 0.00]
 [0.00 0.31 0.68]
 [0.00 0.40 0.60]
 [0.02 0.61 0.37]
 [0.04 0.73 0.23]
 [0.01 0.48 0.51]
 [0.14 0.72 0.14]
 [0.00 0.42 0.58]
 [0.00 0.29 0.71]
 [0.97 0.03 0.00]
 [0.12 0.72 0.17]
 [0.96 0.04 0.00]
 [0.99 0.01 0.00]
 [0.01 0.46 0.54]
 [0.97 0.03 0.00]
 [0.96 0.04 0.00]
 [0.00 0.32 0.68]
 [0.95 0.05 0.00]
 [0.97 0.03 0.00]]
