In [44]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
x = pd.DataFrame(iris.data, columns=[iris.feature_names])
y = pd.Series(iris.target)

In [45]:
x.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


In [46]:
y.value_counts()

0    50
1    50
2    50
dtype: int64

In [47]:
#pip install keras==2.1.5 -i https://pypi.tuna.tsinghua.edu.cn/simple
#pip install --upgrade pip
#pip install tensorflow
#pip install tf-nightly

In [48]:
import tensorflow
import keras
from keras.utils import np_utils
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D,Dropout
from tensorflow.keras.layers import Dense, Activation, Flatten
from tensorflow.keras.utils import to_categorical
from tensorflow.keras import backend as K 
from sklearn.model_selection import train_test_split
from tensorflow.keras import callbacks
y_convertido = np_utils.to_categorical(y) #convertendo a coluna de valores em uma matriz de classes (one hot encoding)

In [49]:
y_convertido

array([[1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
       [1.00, 0.00, 0.00],
 

In [50]:
from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y_convertido, test_size = 0.3)# 30% para teste

In [51]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

In [52]:
modelo = Sequential()
#Construimos a rede neural adicionando camadas por meio do comando ".add". O primeiro argumento consiste no nùmero de neurônios
#que aquela camada terá. Também podemos informar o modelo de inicialização das variáveis e a função de ativação nessa camada.
modelo.add(Dense(10, input_dim=4, kernel_initializer='normal', activation='sigmoid')) #input_dim é a quantidade de neurônios de
#entrada, que nesse caso são 4 variáveis preditoras
modelo.add(Dense(3, kernel_initializer='normal', activation='sigmoid')) #Essa é a saida (3 neurônios pois são 3 classes)
#A função softmax para a saída costuma ser usada em problemas de classificação. Ela dá como resultado probabilidades de pertencer
#a cada uma das classes.

In [53]:
otimizador = keras.optimizers.SGD()

In [ ]:
modelo.compile(loss='categorical_crossentropy', optimizer=otimizador, metrics=['acc']) #"acc" é a metrica de acurácia
modelo.fit(x_treino, y_treino, epochs=1000, batch_size=105, validation_data=(x_teste, y_teste), verbose=1)

Epoch 1/1000
1/1 [==============================] - 0s 417ms/step - loss: 1.0975 - acc: 0.3524 - val_loss: 1.1009 - val_acc: 0.2889
Epoch 2/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0975 - acc: 0.3524 - val_loss: 1.1009 - val_acc: 0.2889
Epoch 3/1000
1/1 [==============================] - 0s 28ms/step - loss: 1.0975 - acc: 0.3524 - val_loss: 1.1009 - val_acc: 0.2889
Epoch 4/1000
1/1 [==============================] - 0s 28ms/step - loss: 1.0974 - acc: 0.3524 - val_loss: 1.1009 - val_acc: 0.2889
Epoch 5/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0974 - acc: 0.3524 - val_loss: 1.1010 - val_acc: 0.2889
Epoch 6/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0973 - acc: 0.3524 - val_loss: 1.1010 - val_acc: 0.2889
Epoch 7/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0973 - acc: 0.3524 - val_loss: 1.1010 - val_acc: 0.2889
Epoch 8/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0972 - 

1/1 [==============================] - 0s 25ms/step - loss: 1.0949 - acc: 0.3524 - val_loss: 1.1010 - val_acc: 0.2889
Epoch 64/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0949 - acc: 0.3524 - val_loss: 1.1010 - val_acc: 0.2889
Epoch 65/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0948 - acc: 0.3524 - val_loss: 1.1009 - val_acc: 0.2889
Epoch 66/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0948 - acc: 0.3524 - val_loss: 1.1009 - val_acc: 0.2889
Epoch 67/1000
1/1 [==============================] - 0s 23ms/step - loss: 1.0947 - acc: 0.3524 - val_loss: 1.1009 - val_acc: 0.2889
Epoch 68/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0947 - acc: 0.3524 - val_loss: 1.1009 - val_acc: 0.2889
Epoch 69/1000
1/1 [==============================] - 0s 24ms/step - loss: 1.0947 - acc: 0.3524 - val_loss: 1.1009 - val_acc: 0.2889
Epoch 70/1000
1/1 [==============================] - 0s 24ms/step - loss: 1.0946 - acc: 0.

Epoch 125/1000
1/1 [==============================] - 0s 30ms/step - loss: 1.0923 - acc: 0.3524 - val_loss: 1.0997 - val_acc: 0.2889
Epoch 126/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0922 - acc: 0.3524 - val_loss: 1.0997 - val_acc: 0.2889
Epoch 127/1000
1/1 [==============================] - 0s 30ms/step - loss: 1.0922 - acc: 0.3524 - val_loss: 1.0997 - val_acc: 0.2889
Epoch 128/1000
1/1 [==============================] - 0s 32ms/step - loss: 1.0921 - acc: 0.3524 - val_loss: 1.0997 - val_acc: 0.2889
Epoch 129/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0921 - acc: 0.3524 - val_loss: 1.0996 - val_acc: 0.2889
Epoch 130/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0920 - acc: 0.3524 - val_loss: 1.0996 - val_acc: 0.2889
Epoch 131/1000
1/1 [==============================] - 0s 24ms/step - loss: 1.0920 - acc: 0.3524 - val_loss: 1.0996 - val_acc: 0.2889
Epoch 132/1000
1/1 [==============================] - 0s 25ms/step - 

1/1 [==============================] - 0s 26ms/step - loss: 1.0892 - acc: 0.3524 - val_loss: 1.0976 - val_acc: 0.2889
Epoch 187/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0892 - acc: 0.3524 - val_loss: 1.0975 - val_acc: 0.2889
Epoch 188/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0891 - acc: 0.3524 - val_loss: 1.0975 - val_acc: 0.2889
Epoch 189/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0891 - acc: 0.3524 - val_loss: 1.0974 - val_acc: 0.2889
Epoch 190/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0890 - acc: 0.3524 - val_loss: 1.0974 - val_acc: 0.2889
Epoch 191/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0890 - acc: 0.3524 - val_loss: 1.0973 - val_acc: 0.2889
Epoch 192/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0889 - acc: 0.3524 - val_loss: 1.0973 - val_acc: 0.2889
Epoch 193/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0889 - 

Epoch 248/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0854 - acc: 0.3524 - val_loss: 1.0944 - val_acc: 0.2889
Epoch 249/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0853 - acc: 0.3524 - val_loss: 1.0943 - val_acc: 0.2889
Epoch 250/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0853 - acc: 0.3524 - val_loss: 1.0942 - val_acc: 0.2889
Epoch 251/1000
1/1 [==============================] - 0s 24ms/step - loss: 1.0852 - acc: 0.3524 - val_loss: 1.0942 - val_acc: 0.2889
Epoch 252/1000
1/1 [==============================] - 0s 24ms/step - loss: 1.0851 - acc: 0.3524 - val_loss: 1.0941 - val_acc: 0.2889
Epoch 253/1000
1/1 [==============================] - 0s 24ms/step - loss: 1.0851 - acc: 0.3524 - val_loss: 1.0941 - val_acc: 0.2889
Epoch 254/1000
1/1 [==============================] - 0s 23ms/step - loss: 1.0850 - acc: 0.3524 - val_loss: 1.0940 - val_acc: 0.2889
Epoch 255/1000
1/1 [==============================] - 0s 24ms/step - 

1/1 [==============================] - 0s 33ms/step - loss: 1.0807 - acc: 0.3905 - val_loss: 1.0902 - val_acc: 0.3333
Epoch 310/1000
1/1 [==============================] - 0s 35ms/step - loss: 1.0806 - acc: 0.3905 - val_loss: 1.0901 - val_acc: 0.3333
Epoch 311/1000
1/1 [==============================] - 0s 31ms/step - loss: 1.0805 - acc: 0.3905 - val_loss: 1.0900 - val_acc: 0.3333
Epoch 312/1000
1/1 [==============================] - 0s 32ms/step - loss: 1.0804 - acc: 0.3905 - val_loss: 1.0899 - val_acc: 0.3333
Epoch 313/1000
1/1 [==============================] - 0s 34ms/step - loss: 1.0803 - acc: 0.3905 - val_loss: 1.0899 - val_acc: 0.3333
Epoch 314/1000
1/1 [==============================] - 0s 31ms/step - loss: 1.0802 - acc: 0.3905 - val_loss: 1.0898 - val_acc: 0.3333
Epoch 315/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0801 - acc: 0.4000 - val_loss: 1.0897 - val_acc: 0.3333
Epoch 316/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0800 - 

Epoch 371/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0746 - acc: 0.5333 - val_loss: 1.0847 - val_acc: 0.4222
Epoch 372/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0744 - acc: 0.5333 - val_loss: 1.0846 - val_acc: 0.4222
Epoch 373/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0743 - acc: 0.5333 - val_loss: 1.0845 - val_acc: 0.4222
Epoch 374/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0742 - acc: 0.5333 - val_loss: 1.0844 - val_acc: 0.4222
Epoch 375/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0741 - acc: 0.5333 - val_loss: 1.0843 - val_acc: 0.4222
Epoch 376/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0740 - acc: 0.5333 - val_loss: 1.0842 - val_acc: 0.4444
Epoch 377/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0739 - acc: 0.5333 - val_loss: 1.0841 - val_acc: 0.4444
Epoch 378/1000
1/1 [==============================] - 0s 28ms/step - 

1/1 [==============================] - 0s 25ms/step - loss: 1.0671 - acc: 0.6571 - val_loss: 1.0780 - val_acc: 0.5556
Epoch 433/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0669 - acc: 0.6571 - val_loss: 1.0778 - val_acc: 0.5556
Epoch 434/1000
1/1 [==============================] - 0s 23ms/step - loss: 1.0668 - acc: 0.6571 - val_loss: 1.0777 - val_acc: 0.5556
Epoch 435/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0667 - acc: 0.6571 - val_loss: 1.0776 - val_acc: 0.5556
Epoch 436/1000
1/1 [==============================] - 0s 23ms/step - loss: 1.0665 - acc: 0.6571 - val_loss: 1.0775 - val_acc: 0.5556
Epoch 437/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0664 - acc: 0.6667 - val_loss: 1.0773 - val_acc: 0.5556
Epoch 438/1000
1/1 [==============================] - 0s 24ms/step - loss: 1.0663 - acc: 0.6667 - val_loss: 1.0772 - val_acc: 0.5556
Epoch 439/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0661 - 

In [41]:
x_treino.shape

(105, 4)

In [42]:
predicoes = modelo.predict(x_teste)
print(predicoes)

2/2 [==============================] - 0s 2ms/step
[[0.56 0.46 0.43]
 [0.56 0.47 0.43]
 [0.47 0.49 0.49]
 [0.46 0.49 0.49]
 [0.57 0.46 0.43]
 [0.41 0.51 0.52]
 [0.41 0.51 0.52]
 [0.59 0.46 0.41]
 [0.42 0.50 0.52]
 [0.46 0.49 0.49]
 [0.46 0.49 0.49]
 [0.38 0.51 0.54]
 [0.46 0.49 0.49]
 [0.56 0.47 0.43]
 [0.41 0.51 0.52]
 [0.57 0.46 0.43]
 [0.42 0.50 0.52]
 [0.56 0.46 0.43]
 [0.48 0.49 0.48]
 [0.44 0.50 0.51]
 [0.44 0.50 0.50]
 [0.40 0.51 0.53]
 [0.57 0.46 0.43]
 [0.43 0.50 0.51]
 [0.57 0.46 0.42]
 [0.44 0.50 0.50]
 [0.39 0.51 0.53]
 [0.40 0.51 0.53]
 [0.44 0.50 0.50]
 [0.55 0.47 0.44]
 [0.42 0.50 0.52]
 [0.57 0.46 0.42]
 [0.42 0.50 0.52]
 [0.41 0.50 0.52]
 [0.57 0.46 0.42]
 [0.44 0.50 0.50]
 [0.40 0.51 0.53]
 [0.39 0.51 0.54]
 [0.47 0.49 0.48]
 [0.58 0.46 0.42]
 [0.57 0.46 0.43]
 [0.45 0.50 0.50]
 [0.40 0.51 0.53]
 [0.40 0.51 0.53]
 [0.41 0.50 0.52]]


In [43]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})
print(predicoes)

[[0.56 0.46 0.43]
 [0.56 0.47 0.43]
 [0.47 0.49 0.49]
 [0.46 0.49 0.49]
 [0.57 0.46 0.43]
 [0.41 0.51 0.52]
 [0.41 0.51 0.52]
 [0.59 0.46 0.41]
 [0.42 0.50 0.52]
 [0.46 0.49 0.49]
 [0.46 0.49 0.49]
 [0.38 0.51 0.54]
 [0.46 0.49 0.49]
 [0.56 0.47 0.43]
 [0.41 0.51 0.52]
 [0.57 0.46 0.43]
 [0.42 0.50 0.52]
 [0.56 0.46 0.43]
 [0.48 0.49 0.48]
 [0.44 0.50 0.51]
 [0.44 0.50 0.50]
 [0.40 0.51 0.53]
 [0.57 0.46 0.43]
 [0.43 0.50 0.51]
 [0.57 0.46 0.42]
 [0.44 0.50 0.50]
 [0.39 0.51 0.53]
 [0.40 0.51 0.53]
 [0.44 0.50 0.50]
 [0.55 0.47 0.44]
 [0.42 0.50 0.52]
 [0.57 0.46 0.42]
 [0.42 0.50 0.52]
 [0.41 0.50 0.52]
 [0.57 0.46 0.42]
 [0.44 0.50 0.50]
 [0.40 0.51 0.53]
 [0.39 0.51 0.54]
 [0.47 0.49 0.48]
 [0.58 0.46 0.42]
 [0.57 0.46 0.43]
 [0.45 0.50 0.50]
 [0.40 0.51 0.53]
 [0.40 0.51 0.53]
 [0.41 0.50 0.52]]
