In [15]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
x = pd.DataFrame(iris.data, columns=[iris.feature_names])
y = pd.Series(iris.target)

In [16]:
x.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


In [17]:
y.value_counts()

0    50
1    50
2    50
Name: count, dtype: int64

In [18]:
# Instale o Anaconda - Ultima versão
# Abra Anaconda Navigator
# Aba - Environments - Crie um novo perfil: tensorflow / python: 3.7
#!pip3 install keras==2.1.5 -i https://pypi.tuna.tsinghua.edu.cn/simple
#!pip3 install tensorflow
#!pip3 install tensorflow-gpu==1.5.0
#!pip3 install tf-nightly
#!pip3 install np_utils

In [19]:
import tensorflow
import keras
from tensorflow.python.keras.utils import np_utils
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D,Dropout
from tensorflow.keras.layers import Dense, Activation, Flatten
from tensorflow.keras.utils import to_categorical
from tensorflow.keras import backend as K 
from sklearn.model_selection import train_test_split
from tensorflow.keras import callbacks
y_convertido = np_utils.to_categorical(y) #convertendo a coluna de valores em uma matriz de classes (one hot encoding)

In [20]:
y_convertido

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [21]:
from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y_convertido, test_size = 0.3)# 30% para teste

In [22]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

In [23]:
modelo = Sequential()
#Construimos a rede neural adicionando camadas por meio do comando ".add". O primeiro argumento consiste no nùmero de neurônios
#que aquela camada terá. Também podemos informar o modelo de inicialização das variáveis e a função de ativação nessa camada.
modelo.add(Dense(10, input_dim=4, kernel_initializer='normal', activation='relu')) #input_dim é a quantidade de neurônios de
#entrada, que nesse caso são 4 variáveis preditoras
modelo.add(Dense(3, kernel_initializer='normal', activation='softmax')) #Essa é a saida (3 neurônios pois são 3 classes)
#A função softmax para a saída costuma ser usada em problemas de classificação. Ela dá como resultado probabilidades de pertencer
#a cada uma das classes (softmax / sigmoid / relu)

In [24]:
otimizador = keras.optimizers.SGD()

In [25]:
x_treino.shape

(105, 4)

In [26]:
modelo.compile(loss='categorical_crossentropy', optimizer=otimizador, metrics=['acc']) #"acc" é a metrica de acurácia
modelo.fit(x_treino, y_treino, epochs=1000, batch_size=105, validation_data=(x_teste, y_teste), verbose=1)

Epoch 1/1000


1/1 [==============================] - 1s 608ms/step - loss: 1.0944 - acc: 0.6952 - val_loss: 1.1010 - val_acc: 0.5556
Epoch 2/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0940 - acc: 0.6952 - val_loss: 1.1005 - val_acc: 0.5556
Epoch 3/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0935 - acc: 0.6952 - val_loss: 1.1000 - val_acc: 0.5556
Epoch 4/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0930 - acc: 0.6857 - val_loss: 1.0996 - val_acc: 0.5111
Epoch 5/1000
1/1 [==============================] - 0s 28ms/step - loss: 1.0926 - acc: 0.6476 - val_loss: 1.0993 - val_acc: 0.4444
Epoch 6/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0923 - acc: 0.5333 - val_loss: 1.0991 - val_acc: 0.3778
Epoch 7/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0919 - acc: 0.4762 - val_loss: 1.0989 - val_acc: 0.2667
Epoch 8/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0916 

1/1 [==============================] - 0s 30ms/step - loss: 1.0744 - acc: 0.3810 - val_loss: 1.0866 - val_acc: 0.2222
Epoch 60/1000
1/1 [==============================] - 0s 28ms/step - loss: 1.0740 - acc: 0.3810 - val_loss: 1.0863 - val_acc: 0.2222
Epoch 61/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0736 - acc: 0.3810 - val_loss: 1.0859 - val_acc: 0.2222
Epoch 62/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0731 - acc: 0.3810 - val_loss: 1.0856 - val_acc: 0.2222
Epoch 63/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0727 - acc: 0.3810 - val_loss: 1.0853 - val_acc: 0.2222
Epoch 64/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0723 - acc: 0.3810 - val_loss: 1.0850 - val_acc: 0.2222
Epoch 65/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0719 - acc: 0.3810 - val_loss: 1.0846 - val_acc: 0.2222
Epoch 66/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0714 - acc: 0.

1/1 [==============================] - 0s 29ms/step - loss: 1.0377 - acc: 0.4000 - val_loss: 1.0528 - val_acc: 0.2222
Epoch 122/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0369 - acc: 0.4000 - val_loss: 1.0520 - val_acc: 0.2222
Epoch 123/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0361 - acc: 0.4000 - val_loss: 1.0511 - val_acc: 0.2222
Epoch 124/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0352 - acc: 0.4000 - val_loss: 1.0502 - val_acc: 0.2222
Epoch 125/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0343 - acc: 0.4000 - val_loss: 1.0493 - val_acc: 0.2444
Epoch 126/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0334 - acc: 0.4000 - val_loss: 1.0484 - val_acc: 0.2444
Epoch 127/1000
1/1 [==============================] - 0s 30ms/step - loss: 1.0325 - acc: 0.4095 - val_loss: 1.0474 - val_acc: 0.2444
Epoch 128/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0316 - 

Epoch 183/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.9639 - acc: 0.7048 - val_loss: 0.9714 - val_acc: 0.5778
Epoch 184/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.9623 - acc: 0.7048 - val_loss: 0.9696 - val_acc: 0.5778
Epoch 185/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.9607 - acc: 0.7048 - val_loss: 0.9677 - val_acc: 0.5778
Epoch 186/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.9591 - acc: 0.7048 - val_loss: 0.9659 - val_acc: 0.5778
Epoch 187/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.9574 - acc: 0.7048 - val_loss: 0.9641 - val_acc: 0.5778
Epoch 188/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.9558 - acc: 0.7048 - val_loss: 0.9622 - val_acc: 0.5778
Epoch 189/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.9542 - acc: 0.7048 - val_loss: 0.9603 - val_acc: 0.5778
Epoch 190/1000
1/1 [==============================] - 0s 26ms/step - 

1/1 [==============================] - 0s 28ms/step - loss: 0.8457 - acc: 0.7429 - val_loss: 0.8362 - val_acc: 0.6667
Epoch 245/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.8435 - acc: 0.7524 - val_loss: 0.8337 - val_acc: 0.6889
Epoch 246/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.8413 - acc: 0.7524 - val_loss: 0.8311 - val_acc: 0.7111
Epoch 247/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.8390 - acc: 0.7524 - val_loss: 0.8286 - val_acc: 0.7111
Epoch 248/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.8368 - acc: 0.7714 - val_loss: 0.8260 - val_acc: 0.7333
Epoch 249/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.8346 - acc: 0.7714 - val_loss: 0.8235 - val_acc: 0.7333
Epoch 250/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.8323 - acc: 0.8000 - val_loss: 0.8209 - val_acc: 0.7556
Epoch 251/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.8301 - 

Epoch 306/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.7081 - acc: 0.9619 - val_loss: 0.6819 - val_acc: 0.9333
Epoch 307/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.7060 - acc: 0.9619 - val_loss: 0.6796 - val_acc: 0.9333
Epoch 308/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.7039 - acc: 0.9619 - val_loss: 0.6774 - val_acc: 0.9556
Epoch 309/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.7019 - acc: 0.9714 - val_loss: 0.6751 - val_acc: 0.9556
Epoch 310/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.6999 - acc: 0.9714 - val_loss: 0.6729 - val_acc: 0.9556
Epoch 311/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.6978 - acc: 0.9714 - val_loss: 0.6707 - val_acc: 0.9556
Epoch 312/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.6958 - acc: 0.9714 - val_loss: 0.6685 - val_acc: 0.9778
Epoch 313/1000
1/1 [==============================] - 0s 27ms/step - 

1/1 [==============================] - 0s 26ms/step - loss: 0.6010 - acc: 0.9810 - val_loss: 0.5685 - val_acc: 0.9556
Epoch 368/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5996 - acc: 0.9810 - val_loss: 0.5670 - val_acc: 0.9556
Epoch 369/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.5982 - acc: 0.9810 - val_loss: 0.5656 - val_acc: 0.9556
Epoch 370/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5968 - acc: 0.9810 - val_loss: 0.5641 - val_acc: 0.9556
Epoch 371/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.5954 - acc: 0.9810 - val_loss: 0.5627 - val_acc: 0.9556
Epoch 372/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5940 - acc: 0.9810 - val_loss: 0.5613 - val_acc: 0.9556
Epoch 373/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5926 - acc: 0.9810 - val_loss: 0.5599 - val_acc: 0.9556
Epoch 374/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.5912 - 

Epoch 429/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5278 - acc: 0.9810 - val_loss: 0.4960 - val_acc: 0.9778
Epoch 430/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5269 - acc: 0.9810 - val_loss: 0.4951 - val_acc: 0.9778
Epoch 431/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5259 - acc: 0.9810 - val_loss: 0.4942 - val_acc: 0.9778
Epoch 432/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5249 - acc: 0.9810 - val_loss: 0.4932 - val_acc: 0.9778
Epoch 433/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.5240 - acc: 0.9810 - val_loss: 0.4923 - val_acc: 0.9778
Epoch 434/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.5231 - acc: 0.9810 - val_loss: 0.4914 - val_acc: 0.9778
Epoch 435/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5221 - acc: 0.9810 - val_loss: 0.4905 - val_acc: 0.9778
Epoch 436/1000
1/1 [==============================] - 0s 28ms/step - 

1/1 [==============================] - 0s 26ms/step - loss: 0.4773 - acc: 0.9810 - val_loss: 0.4482 - val_acc: 0.9778
Epoch 491/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.4766 - acc: 0.9810 - val_loss: 0.4475 - val_acc: 0.9778
Epoch 492/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.4759 - acc: 0.9810 - val_loss: 0.4469 - val_acc: 0.9778
Epoch 493/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.4752 - acc: 0.9810 - val_loss: 0.4462 - val_acc: 0.9778
Epoch 494/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.4745 - acc: 0.9810 - val_loss: 0.4456 - val_acc: 0.9778
Epoch 495/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.4738 - acc: 0.9810 - val_loss: 0.4449 - val_acc: 0.9778
Epoch 496/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.4731 - acc: 0.9810 - val_loss: 0.4443 - val_acc: 0.9778
Epoch 497/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.4724 - 

Epoch 552/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.4375 - acc: 0.9810 - val_loss: 0.4115 - val_acc: 0.9778
Epoch 553/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.4369 - acc: 0.9810 - val_loss: 0.4109 - val_acc: 0.9778
Epoch 554/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.4363 - acc: 0.9810 - val_loss: 0.4104 - val_acc: 0.9778
Epoch 555/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.4357 - acc: 0.9810 - val_loss: 0.4099 - val_acc: 0.9778
Epoch 556/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.4351 - acc: 0.9810 - val_loss: 0.4094 - val_acc: 0.9778
Epoch 557/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.4346 - acc: 0.9810 - val_loss: 0.4089 - val_acc: 0.9778
Epoch 558/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.4340 - acc: 0.9810 - val_loss: 0.4083 - val_acc: 0.9778
Epoch 559/1000
1/1 [==============================] - 0s 28ms/step - 

1/1 [==============================] - 0s 27ms/step - loss: 0.4042 - acc: 0.9810 - val_loss: 0.3816 - val_acc: 0.9778
Epoch 614/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.4037 - acc: 0.9810 - val_loss: 0.3811 - val_acc: 0.9778
Epoch 615/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.4032 - acc: 0.9810 - val_loss: 0.3807 - val_acc: 0.9778
Epoch 616/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.4027 - acc: 0.9810 - val_loss: 0.3802 - val_acc: 0.9778
Epoch 617/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.4022 - acc: 0.9810 - val_loss: 0.3797 - val_acc: 0.9778
Epoch 618/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.4017 - acc: 0.9810 - val_loss: 0.3793 - val_acc: 0.9778
Epoch 619/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.4012 - acc: 0.9810 - val_loss: 0.3788 - val_acc: 0.9778
Epoch 620/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.4007 - 

Epoch 675/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.3740 - acc: 0.9810 - val_loss: 0.3541 - val_acc: 0.9778
Epoch 676/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.3735 - acc: 0.9810 - val_loss: 0.3537 - val_acc: 0.9778
Epoch 677/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.3730 - acc: 0.9810 - val_loss: 0.3533 - val_acc: 0.9778
Epoch 678/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.3726 - acc: 0.9810 - val_loss: 0.3529 - val_acc: 0.9778
Epoch 679/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.3721 - acc: 0.9810 - val_loss: 0.3525 - val_acc: 0.9778
Epoch 680/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.3716 - acc: 0.9810 - val_loss: 0.3521 - val_acc: 0.9778
Epoch 681/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.3712 - acc: 0.9810 - val_loss: 0.3517 - val_acc: 0.9778
Epoch 682/1000
1/1 [==============================] - 0s 27ms/step - 

1/1 [==============================] - 0s 25ms/step - loss: 0.3465 - acc: 0.9810 - val_loss: 0.3299 - val_acc: 0.9778
Epoch 737/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.3461 - acc: 0.9810 - val_loss: 0.3295 - val_acc: 0.9778
Epoch 738/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.3456 - acc: 0.9810 - val_loss: 0.3292 - val_acc: 0.9778
Epoch 739/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.3452 - acc: 0.9810 - val_loss: 0.3288 - val_acc: 0.9778
Epoch 740/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.3448 - acc: 0.9810 - val_loss: 0.3284 - val_acc: 0.9778
Epoch 741/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.3443 - acc: 0.9810 - val_loss: 0.3280 - val_acc: 0.9778
Epoch 742/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.3439 - acc: 0.9810 - val_loss: 0.3277 - val_acc: 0.9778
Epoch 743/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.3435 - 

Epoch 798/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.3206 - acc: 0.9810 - val_loss: 0.3072 - val_acc: 0.9778
Epoch 799/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.3202 - acc: 0.9810 - val_loss: 0.3068 - val_acc: 0.9778
Epoch 800/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.3198 - acc: 0.9810 - val_loss: 0.3065 - val_acc: 0.9778
Epoch 801/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.3194 - acc: 0.9810 - val_loss: 0.3061 - val_acc: 0.9778
Epoch 802/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.3190 - acc: 0.9810 - val_loss: 0.3058 - val_acc: 0.9778
Epoch 803/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.3186 - acc: 0.9810 - val_loss: 0.3054 - val_acc: 0.9778
Epoch 804/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.3182 - acc: 0.9810 - val_loss: 0.3051 - val_acc: 0.9778
Epoch 805/1000
1/1 [==============================] - 0s 27ms/step - 

1/1 [==============================] - 0s 27ms/step - loss: 0.2969 - acc: 0.9810 - val_loss: 0.2867 - val_acc: 0.9778
Epoch 860/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.2966 - acc: 0.9810 - val_loss: 0.2864 - val_acc: 0.9778
Epoch 861/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.2962 - acc: 0.9810 - val_loss: 0.2861 - val_acc: 0.9778
Epoch 862/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.2958 - acc: 0.9810 - val_loss: 0.2857 - val_acc: 0.9778
Epoch 863/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.2955 - acc: 0.9810 - val_loss: 0.2854 - val_acc: 0.9778
Epoch 864/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.2951 - acc: 0.9810 - val_loss: 0.2851 - val_acc: 0.9778
Epoch 865/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.2947 - acc: 0.9810 - val_loss: 0.2848 - val_acc: 0.9778
Epoch 866/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.2943 - 

Epoch 921/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.2748 - acc: 0.9810 - val_loss: 0.2678 - val_acc: 0.9778
Epoch 922/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.2745 - acc: 0.9810 - val_loss: 0.2675 - val_acc: 0.9778
Epoch 923/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.2741 - acc: 0.9810 - val_loss: 0.2672 - val_acc: 0.9778
Epoch 924/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.2738 - acc: 0.9810 - val_loss: 0.2669 - val_acc: 0.9778
Epoch 925/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.2734 - acc: 0.9810 - val_loss: 0.2667 - val_acc: 0.9778
Epoch 926/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.2731 - acc: 0.9810 - val_loss: 0.2664 - val_acc: 0.9778
Epoch 927/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.2728 - acc: 0.9810 - val_loss: 0.2661 - val_acc: 0.9778
Epoch 928/1000
1/1 [==============================] - 0s 25ms/step - 

1/1 [==============================] - 0s 29ms/step - loss: 0.2549 - acc: 0.9905 - val_loss: 0.2511 - val_acc: 0.9778
Epoch 983/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.2546 - acc: 0.9905 - val_loss: 0.2509 - val_acc: 0.9778
Epoch 984/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.2543 - acc: 0.9905 - val_loss: 0.2506 - val_acc: 0.9778
Epoch 985/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.2540 - acc: 0.9905 - val_loss: 0.2504 - val_acc: 0.9778
Epoch 986/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.2537 - acc: 0.9905 - val_loss: 0.2501 - val_acc: 0.9778
Epoch 987/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.2534 - acc: 0.9905 - val_loss: 0.2499 - val_acc: 0.9778
Epoch 988/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.2530 - acc: 0.9905 - val_loss: 0.2496 - val_acc: 0.9778
Epoch 989/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.2527 - 

In [27]:
predicoes = modelo.predict(x_teste) #Aplicar previsões
print(predicoes)

2/2 [==============================] - 0s 3ms/step
[[6.3863501e-04 2.6625425e-01 7.3310709e-01]
 [9.5853704e-01 4.1389070e-02 7.3950570e-05]
 [2.8186366e-03 4.7965664e-01 5.1752466e-01]
 [2.5170538e-04 2.3510496e-01 7.6464337e-01]
 [1.2504534e-03 3.2119018e-01 6.7755938e-01]
 [9.0348523e-04 2.5484911e-01 7.4424744e-01]
 [9.6468115e-01 3.5286348e-02 3.2424730e-05]
 [9.7473097e-01 2.5248945e-02 2.0131407e-05]
 [9.7386974e-01 2.6110239e-02 2.0104988e-05]
 [2.9087483e-04 1.6334014e-01 8.3636898e-01]
 [9.3478674e-01 6.5066226e-02 1.4692829e-04]
 [9.5486182e-01 4.5064300e-02 7.3843228e-05]
 [9.1730664e-03 5.6432247e-01 4.2650446e-01]
 [9.5192623e-01 4.7997810e-02 7.6041317e-05]
 [9.5291370e-01 4.7009084e-02 7.7282944e-05]
 [5.0448656e-02 7.7197856e-01 1.7757277e-01]
 [9.4152182e-01 5.8389839e-02 8.8322362e-05]
 [2.2921390e-03 4.7115302e-01 5.2655488e-01]
 [2.5734486e-02 7.4635202e-01 2.2791347e-01]
 [1.1241709e-05 7.0629045e-02 9.2935979e-01]
 [3.6500054e-04 2.1478106e-01 7.8485399e-01]
 [9.

In [28]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})#Imprimir somente duas casas decimais.
print(predicoes)

[[0.00 0.27 0.73]
 [0.96 0.04 0.00]
 [0.00 0.48 0.52]
 [0.00 0.24 0.76]
 [0.00 0.32 0.68]
 [0.00 0.25 0.74]
 [0.96 0.04 0.00]
 [0.97 0.03 0.00]
 [0.97 0.03 0.00]
 [0.00 0.16 0.84]
 [0.93 0.07 0.00]
 [0.95 0.05 0.00]
 [0.01 0.56 0.43]
 [0.95 0.05 0.00]
 [0.95 0.05 0.00]
 [0.05 0.77 0.18]
 [0.94 0.06 0.00]
 [0.00 0.47 0.53]
 [0.03 0.75 0.23]
 [0.00 0.07 0.93]
 [0.00 0.21 0.78]
 [0.01 0.63 0.36]
 [0.00 0.30 0.69]
 [0.01 0.59 0.41]
 [0.03 0.74 0.24]
 [0.00 0.15 0.85]
 [0.99 0.01 0.00]
 [0.00 0.51 0.48]
 [0.05 0.79 0.17]
 [0.96 0.04 0.00]
 [0.97 0.03 0.00]
 [0.97 0.03 0.00]
 [0.00 0.16 0.83]
 [0.00 0.32 0.68]
 [0.08 0.76 0.16]
 [0.96 0.04 0.00]
 [0.95 0.05 0.00]
 [0.97 0.03 0.00]
 [0.00 0.33 0.67]
 [0.00 0.26 0.74]
 [0.00 0.12 0.88]
 [0.00 0.43 0.57]
 [0.00 0.10 0.90]
 [0.00 0.22 0.78]
 [0.00 0.18 0.82]]
