In [1]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
x = pd.DataFrame(iris.data, columns=[iris.feature_names])
y = pd.Series(iris.target)

In [2]:
x.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


In [3]:
y.value_counts()

0    50
1    50
2    50
dtype: int64

In [4]:
#pip install keras==2.1.5 -i https://pypi.tuna.tsinghua.edu.cn/simple
#pip install --upgrade pip
#pip install tensorflow
#pip install tf-nightly

In [5]:
import tensorflow
import keras
from keras.utils import np_utils
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D,Dropout
from tensorflow.keras.layers import Dense, Activation, Flatten
from tensorflow.keras.utils import to_categorical
from tensorflow.keras import backend as K 
from sklearn.model_selection import train_test_split
from tensorflow.keras import callbacks
y_convertido = np_utils.to_categorical(y) #convertendo a coluna de valores em uma matriz de classes (one hot encoding)

Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.


In [6]:
y_convertido

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [7]:
from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y_convertido, test_size = 0.3)# 30% para teste

In [8]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

In [9]:
modelo = Sequential()
#Construimos a rede neural adicionando camadas por meio do comando ".add". O primeiro argumento consiste no nùmero de neurônios
#que aquela camada terá. Também podemos informar o modelo de inicialização das variáveis e a função de ativação nessa camada.
modelo.add(Dense(10, input_dim=4, kernel_initializer='normal', activation='relu')) #input_dim é a quantidade de neurônios de
#entrada, que nesse caso são 4 variáveis preditoras
modelo.add(Dense(3, kernel_initializer='normal', activation='softmax')) #Essa é a saida (3 neurônios pois são 3 classes)
#A função softmax para a saída costuma ser usada em problemas de classificação. Ela dá como resultado probabilidades de pertencer
#a cada uma das classes (softmax / sigmoid / relu)

In [10]:
otimizador = keras.optimizers.SGD()

In [11]:
x_treino.shape

(105, 4)

In [12]:
modelo.compile(loss='categorical_crossentropy', optimizer=otimizador, metrics=['acc']) #"acc" é a metrica de acurácia
modelo.fit(x_treino, y_treino, epochs=1000, batch_size=105, validation_data=(x_teste, y_teste), verbose=1)

Epoch 1/1000
1/1 [==============================] - 0s 495ms/step - loss: 1.0952 - acc: 0.3429 - val_loss: 1.0952 - val_acc: 0.3111
Epoch 2/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0949 - acc: 0.3429 - val_loss: 1.0950 - val_acc: 0.3111
Epoch 3/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0945 - acc: 0.3429 - val_loss: 1.0948 - val_acc: 0.3111
Epoch 4/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0942 - acc: 0.3429 - val_loss: 1.0945 - val_acc: 0.3111
Epoch 5/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0938 - acc: 0.3429 - val_loss: 1.0943 - val_acc: 0.3111
Epoch 6/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0935 - acc: 0.3429 - val_loss: 1.0941 - val_acc: 0.3111
Epoch 7/1000
1/1 [==============================] - 0s 30ms/step - loss: 1.0931 - acc: 0.3429 - val_loss: 1.0939 - val_acc: 0.3111
Epoch 8/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0928 - 

1/1 [==============================] - 0s 23ms/step - loss: 1.0703 - acc: 0.3429 - val_loss: 1.0780 - val_acc: 0.3111
Epoch 64/1000
1/1 [==============================] - 0s 23ms/step - loss: 1.0698 - acc: 0.3429 - val_loss: 1.0777 - val_acc: 0.3111
Epoch 65/1000
1/1 [==============================] - 0s 24ms/step - loss: 1.0693 - acc: 0.3429 - val_loss: 1.0773 - val_acc: 0.3111
Epoch 66/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0688 - acc: 0.3429 - val_loss: 1.0770 - val_acc: 0.3111
Epoch 67/1000
1/1 [==============================] - 0s 24ms/step - loss: 1.0683 - acc: 0.3429 - val_loss: 1.0766 - val_acc: 0.3111
Epoch 68/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0678 - acc: 0.3429 - val_loss: 1.0762 - val_acc: 0.3111
Epoch 69/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0673 - acc: 0.3429 - val_loss: 1.0758 - val_acc: 0.3111
Epoch 70/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0668 - acc: 0.

Epoch 125/1000
1/1 [==============================] - 0s 24ms/step - loss: 1.0301 - acc: 0.3429 - val_loss: 1.0449 - val_acc: 0.3111
Epoch 126/1000
1/1 [==============================] - 0s 24ms/step - loss: 1.0293 - acc: 0.3429 - val_loss: 1.0441 - val_acc: 0.3111
Epoch 127/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.0285 - acc: 0.3429 - val_loss: 1.0433 - val_acc: 0.3111
Epoch 128/1000
1/1 [==============================] - 0s 23ms/step - loss: 1.0276 - acc: 0.3429 - val_loss: 1.0425 - val_acc: 0.3111
Epoch 129/1000
1/1 [==============================] - 0s 24ms/step - loss: 1.0268 - acc: 0.3429 - val_loss: 1.0418 - val_acc: 0.3111
Epoch 130/1000
1/1 [==============================] - 0s 23ms/step - loss: 1.0259 - acc: 0.3429 - val_loss: 1.0410 - val_acc: 0.3111
Epoch 131/1000
1/1 [==============================] - 0s 24ms/step - loss: 1.0251 - acc: 0.3429 - val_loss: 1.0401 - val_acc: 0.3111
Epoch 132/1000
1/1 [==============================] - 0s 23ms/step - 

1/1 [==============================] - 0s 24ms/step - loss: 0.9637 - acc: 0.4571 - val_loss: 0.9769 - val_acc: 0.4889
Epoch 187/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.9623 - acc: 0.4762 - val_loss: 0.9753 - val_acc: 0.5111
Epoch 188/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.9608 - acc: 0.4762 - val_loss: 0.9738 - val_acc: 0.5111
Epoch 189/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.9594 - acc: 0.5048 - val_loss: 0.9722 - val_acc: 0.5556
Epoch 190/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.9579 - acc: 0.5238 - val_loss: 0.9706 - val_acc: 0.5556
Epoch 191/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.9565 - acc: 0.5333 - val_loss: 0.9690 - val_acc: 0.5778
Epoch 192/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.9550 - acc: 0.5333 - val_loss: 0.9674 - val_acc: 0.5778
Epoch 193/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.9535 - 

Epoch 248/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.8592 - acc: 0.6571 - val_loss: 0.8635 - val_acc: 0.6889
Epoch 249/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.8574 - acc: 0.6571 - val_loss: 0.8616 - val_acc: 0.6889
Epoch 250/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.8556 - acc: 0.6571 - val_loss: 0.8597 - val_acc: 0.6889
Epoch 251/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.8539 - acc: 0.6571 - val_loss: 0.8578 - val_acc: 0.6889
Epoch 252/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.8521 - acc: 0.6571 - val_loss: 0.8559 - val_acc: 0.6889
Epoch 253/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.8503 - acc: 0.6571 - val_loss: 0.8539 - val_acc: 0.6889
Epoch 254/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.8485 - acc: 0.6571 - val_loss: 0.8520 - val_acc: 0.6889
Epoch 255/1000
1/1 [==============================] - 0s 25ms/step - 

1/1 [==============================] - 0s 25ms/step - loss: 0.7469 - acc: 0.6571 - val_loss: 0.7403 - val_acc: 0.6889
Epoch 310/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.7450 - acc: 0.6571 - val_loss: 0.7382 - val_acc: 0.6889
Epoch 311/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.7432 - acc: 0.6571 - val_loss: 0.7361 - val_acc: 0.6889
Epoch 312/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.7413 - acc: 0.6571 - val_loss: 0.7341 - val_acc: 0.6889
Epoch 313/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.7394 - acc: 0.6571 - val_loss: 0.7320 - val_acc: 0.6889
Epoch 314/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.7376 - acc: 0.6571 - val_loss: 0.7299 - val_acc: 0.6889
Epoch 315/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.7357 - acc: 0.6571 - val_loss: 0.7278 - val_acc: 0.6889
Epoch 316/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.7338 - 

Epoch 371/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.6388 - acc: 0.6952 - val_loss: 0.6202 - val_acc: 0.7111
Epoch 372/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.6373 - acc: 0.6952 - val_loss: 0.6185 - val_acc: 0.7111
Epoch 373/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.6357 - acc: 0.6952 - val_loss: 0.6168 - val_acc: 0.7111
Epoch 374/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.6342 - acc: 0.6952 - val_loss: 0.6151 - val_acc: 0.7111
Epoch 375/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.6327 - acc: 0.6952 - val_loss: 0.6134 - val_acc: 0.7111
Epoch 376/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.6312 - acc: 0.6952 - val_loss: 0.6118 - val_acc: 0.7111
Epoch 377/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.6297 - acc: 0.6952 - val_loss: 0.6101 - val_acc: 0.7111
Epoch 378/1000
1/1 [==============================] - 0s 26ms/step - 

1/1 [==============================] - 0s 26ms/step - loss: 0.5588 - acc: 0.7238 - val_loss: 0.5334 - val_acc: 0.7556
Epoch 433/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.5577 - acc: 0.7238 - val_loss: 0.5322 - val_acc: 0.7556
Epoch 434/1000
1/1 [==============================] - 0s 35ms/step - loss: 0.5566 - acc: 0.7333 - val_loss: 0.5311 - val_acc: 0.7556
Epoch 435/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5555 - acc: 0.7333 - val_loss: 0.5299 - val_acc: 0.7556
Epoch 436/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.5544 - acc: 0.7333 - val_loss: 0.5288 - val_acc: 0.7556
Epoch 437/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5534 - acc: 0.7333 - val_loss: 0.5277 - val_acc: 0.7556
Epoch 438/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5523 - acc: 0.7429 - val_loss: 0.5265 - val_acc: 0.7556
Epoch 439/1000
1/1 [==============================] - 0s 34ms/step - loss: 0.5512 - 

Epoch 494/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.5014 - acc: 0.8381 - val_loss: 0.4734 - val_acc: 0.8667
Epoch 495/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.5006 - acc: 0.8381 - val_loss: 0.4725 - val_acc: 0.8667
Epoch 496/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.4998 - acc: 0.8476 - val_loss: 0.4717 - val_acc: 0.8667
Epoch 497/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.4990 - acc: 0.8476 - val_loss: 0.4710 - val_acc: 0.8667
Epoch 498/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.4983 - acc: 0.8476 - val_loss: 0.4702 - val_acc: 0.8667
Epoch 499/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.4975 - acc: 0.8476 - val_loss: 0.4694 - val_acc: 0.8667
Epoch 500/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.4967 - acc: 0.8476 - val_loss: 0.4686 - val_acc: 0.8667
Epoch 501/1000
1/1 [==============================] - 0s 26ms/step - 

1/1 [==============================] - 0s 24ms/step - loss: 0.4592 - acc: 0.8857 - val_loss: 0.4307 - val_acc: 0.9333
Epoch 556/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.4586 - acc: 0.8952 - val_loss: 0.4300 - val_acc: 0.9333
Epoch 557/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.4580 - acc: 0.8952 - val_loss: 0.4294 - val_acc: 0.9333
Epoch 558/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.4574 - acc: 0.8952 - val_loss: 0.4288 - val_acc: 0.9333
Epoch 559/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.4568 - acc: 0.8952 - val_loss: 0.4282 - val_acc: 0.9333
Epoch 560/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.4562 - acc: 0.8952 - val_loss: 0.4276 - val_acc: 0.9333
Epoch 561/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.4556 - acc: 0.8952 - val_loss: 0.4270 - val_acc: 0.9333
Epoch 562/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.4550 - 

Epoch 617/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.4244 - acc: 0.9333 - val_loss: 0.3962 - val_acc: 0.9333
Epoch 618/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.4239 - acc: 0.9333 - val_loss: 0.3957 - val_acc: 0.9333
Epoch 619/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.4234 - acc: 0.9333 - val_loss: 0.3952 - val_acc: 0.9333
Epoch 620/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.4229 - acc: 0.9333 - val_loss: 0.3947 - val_acc: 0.9333
Epoch 621/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.4224 - acc: 0.9333 - val_loss: 0.3942 - val_acc: 0.9333
Epoch 622/1000
1/1 [==============================] - 0s 32ms/step - loss: 0.4219 - acc: 0.9333 - val_loss: 0.3937 - val_acc: 0.9333
Epoch 623/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.4213 - acc: 0.9333 - val_loss: 0.3932 - val_acc: 0.9333
Epoch 624/1000
1/1 [==============================] - 0s 28ms/step - 

1/1 [==============================] - 0s 31ms/step - loss: 0.3947 - acc: 0.9429 - val_loss: 0.3673 - val_acc: 0.9556
Epoch 679/1000
1/1 [==============================] - 0s 32ms/step - loss: 0.3942 - acc: 0.9429 - val_loss: 0.3669 - val_acc: 0.9556
Epoch 680/1000
1/1 [==============================] - 0s 33ms/step - loss: 0.3937 - acc: 0.9429 - val_loss: 0.3665 - val_acc: 0.9556
Epoch 681/1000
1/1 [==============================] - 0s 32ms/step - loss: 0.3933 - acc: 0.9524 - val_loss: 0.3660 - val_acc: 0.9556
Epoch 682/1000
1/1 [==============================] - 0s 32ms/step - loss: 0.3928 - acc: 0.9524 - val_loss: 0.3656 - val_acc: 0.9556
Epoch 683/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.3924 - acc: 0.9524 - val_loss: 0.3651 - val_acc: 0.9556
Epoch 684/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.3919 - acc: 0.9524 - val_loss: 0.3647 - val_acc: 0.9556
Epoch 685/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.3914 - 

Epoch 740/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.3673 - acc: 0.9619 - val_loss: 0.3411 - val_acc: 0.9556
Epoch 741/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.3668 - acc: 0.9619 - val_loss: 0.3407 - val_acc: 0.9556
Epoch 742/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.3664 - acc: 0.9619 - val_loss: 0.3403 - val_acc: 0.9556
Epoch 743/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.3660 - acc: 0.9619 - val_loss: 0.3398 - val_acc: 0.9556
Epoch 744/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.3656 - acc: 0.9619 - val_loss: 0.3394 - val_acc: 0.9778
Epoch 745/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.3652 - acc: 0.9619 - val_loss: 0.3390 - val_acc: 0.9778
Epoch 746/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.3647 - acc: 0.9619 - val_loss: 0.3386 - val_acc: 0.9778
Epoch 747/1000
1/1 [==============================] - 0s 25ms/step - 

1/1 [==============================] - 0s 24ms/step - loss: 0.3425 - acc: 0.9619 - val_loss: 0.3173 - val_acc: 0.9778
Epoch 802/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.3421 - acc: 0.9619 - val_loss: 0.3169 - val_acc: 0.9778
Epoch 803/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.3417 - acc: 0.9619 - val_loss: 0.3165 - val_acc: 0.9778
Epoch 804/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.3413 - acc: 0.9619 - val_loss: 0.3161 - val_acc: 0.9778
Epoch 805/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.3409 - acc: 0.9619 - val_loss: 0.3158 - val_acc: 0.9778
Epoch 806/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.3405 - acc: 0.9619 - val_loss: 0.3154 - val_acc: 0.9778
Epoch 807/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.3401 - acc: 0.9619 - val_loss: 0.3150 - val_acc: 0.9778
Epoch 808/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.3397 - 

Epoch 863/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.3191 - acc: 0.9714 - val_loss: 0.2948 - val_acc: 0.9778
Epoch 864/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.3188 - acc: 0.9714 - val_loss: 0.2945 - val_acc: 0.9778
Epoch 865/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.3184 - acc: 0.9714 - val_loss: 0.2942 - val_acc: 0.9778
Epoch 866/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.3180 - acc: 0.9714 - val_loss: 0.2938 - val_acc: 0.9778
Epoch 867/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.3177 - acc: 0.9714 - val_loss: 0.2935 - val_acc: 0.9778
Epoch 868/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.3173 - acc: 0.9714 - val_loss: 0.2931 - val_acc: 0.9778
Epoch 869/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.3170 - acc: 0.9714 - val_loss: 0.2928 - val_acc: 0.9778
Epoch 870/1000
1/1 [==============================] - 0s 45ms/step - 

1/1 [==============================] - 0s 25ms/step - loss: 0.2980 - acc: 0.9714 - val_loss: 0.2745 - val_acc: 0.9778
Epoch 925/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.2977 - acc: 0.9714 - val_loss: 0.2741 - val_acc: 0.9778
Epoch 926/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.2973 - acc: 0.9714 - val_loss: 0.2738 - val_acc: 0.9778
Epoch 927/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.2970 - acc: 0.9714 - val_loss: 0.2735 - val_acc: 0.9778
Epoch 928/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.2967 - acc: 0.9714 - val_loss: 0.2732 - val_acc: 0.9778
Epoch 929/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.2963 - acc: 0.9714 - val_loss: 0.2729 - val_acc: 0.9778
Epoch 930/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.2960 - acc: 0.9714 - val_loss: 0.2725 - val_acc: 0.9778
Epoch 931/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.2957 - 

Epoch 986/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.2784 - acc: 0.9714 - val_loss: 0.2554 - val_acc: 0.9778
Epoch 987/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.2781 - acc: 0.9714 - val_loss: 0.2551 - val_acc: 0.9778
Epoch 988/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.2778 - acc: 0.9714 - val_loss: 0.2548 - val_acc: 0.9778
Epoch 989/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.2775 - acc: 0.9714 - val_loss: 0.2545 - val_acc: 0.9778
Epoch 990/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.2772 - acc: 0.9714 - val_loss: 0.2542 - val_acc: 0.9778
Epoch 991/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.2769 - acc: 0.9714 - val_loss: 0.2539 - val_acc: 0.9778
Epoch 992/1000
1/1 [==============================] - 0s 23ms/step - loss: 0.2766 - acc: 0.9714 - val_loss: 0.2536 - val_acc: 0.9778
Epoch 993/1000
1/1 [==============================] - 0s 24ms/step - 

In [13]:
predicoes = modelo.predict(x_teste) #Aplicar previsões
print(predicoes)

2/2 [==============================] - 0s 1ms/step
[[9.6509135e-01 3.4836259e-02 7.2399132e-05]
 [9.6177763e-01 3.8128622e-02 9.3791612e-05]
 [8.3257060e-04 3.9772499e-01 6.0144246e-01]
 [7.5907179e-04 2.2950818e-01 7.6973277e-01]
 [3.3320323e-02 7.0838767e-01 2.5829199e-01]
 [5.0164565e-02 7.4610031e-01 2.0373508e-01]
 [5.2797329e-03 4.7940964e-01 5.1531065e-01]
 [9.6629232e-01 3.3641741e-02 6.5865497e-05]
 [9.4904470e-01 5.0775390e-02 1.7993496e-04]
 [9.6661490e-01 3.3320960e-02 6.4232074e-05]
 [9.7993475e-01 2.0050200e-02 1.5108371e-05]
 [9.0851581e-01 9.0959042e-02 5.2513380e-04]
 [3.9960002e-04 2.0901036e-01 7.9059005e-01]
 [9.3014628e-01 6.9535457e-02 3.1820571e-04]
 [3.9084274e-02 6.4698505e-01 3.1393066e-01]
 [6.7293749e-04 3.0904034e-01 6.9028676e-01]
 [9.3411762e-01 6.5615691e-02 2.6673163e-04]
 [4.8971188e-04 2.2141860e-01 7.7809167e-01]
 [2.4490161e-03 4.3613476e-01 5.6141627e-01]
 [2.2370161e-02 6.2993383e-01 3.4769601e-01]
 [9.7292680e-01 2.7037783e-02 3.5430963e-05]
 [4.

In [14]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})#Imprimir somente duas casas decimais.
print(predicoes)

[[0.97 0.03 0.00]
 [0.96 0.04 0.00]
 [0.00 0.40 0.60]
 [0.00 0.23 0.77]
 [0.03 0.71 0.26]
 [0.05 0.75 0.20]
 [0.01 0.48 0.52]
 [0.97 0.03 0.00]
 [0.95 0.05 0.00]
 [0.97 0.03 0.00]
 [0.98 0.02 0.00]
 [0.91 0.09 0.00]
 [0.00 0.21 0.79]
 [0.93 0.07 0.00]
 [0.04 0.65 0.31]
 [0.00 0.31 0.69]
 [0.93 0.07 0.00]
 [0.00 0.22 0.78]
 [0.00 0.44 0.56]
 [0.02 0.63 0.35]
 [0.97 0.03 0.00]
 [0.05 0.76 0.19]
 [0.00 0.19 0.81]
 [0.09 0.77 0.14]
 [0.03 0.69 0.28]
 [0.96 0.04 0.00]
 [0.01 0.55 0.45]
 [0.01 0.58 0.41]
 [0.03 0.73 0.24]
 [0.03 0.68 0.29]
 [0.00 0.27 0.73]
 [0.00 0.23 0.77]
 [0.93 0.07 0.00]
 [0.97 0.03 0.00]
 [0.00 0.34 0.66]
 [0.94 0.06 0.00]
 [0.95 0.05 0.00]
 [0.00 0.30 0.70]
 [0.96 0.04 0.00]
 [0.00 0.22 0.78]
 [0.00 0.26 0.74]
 [0.02 0.63 0.35]
 [0.95 0.05 0.00]
 [0.00 0.21 0.79]
 [0.03 0.63 0.35]]
